# Default Hydra logging configuration for SpectraMind V50
# This enables reproducibility-grade logging: console + file + JSONL
# Optional MLflow/W&B handlers can be added by overriding this config group.

defaults:
  - hydra/job_logging: spectramind_v50
