# Hydra job logger based on standard 'rich' console and RotatingFileHandler for app logs

version: 1
formatters:
  simple:
    format: "[%(asctime)s] [%(levelname)s] %(name)s: %(message)s"
  precise:
    format: "%(asctime)s.%(msecs)03d %(levelname)s %(process)d %(threadName)s %(name)s:%(lineno)d - %(message)s"
handlers:
  console:
    class: rich.logging.RichHandler
    level: ${logging.level}
    rich_tracebacks: true
    markup: true
  file:
    class: logging.handlers.RotatingFileHandler
    level: ${logging.level}
    filename: ${logging.rotating_log_path}
    maxBytes: ${logging.rotating_bytes}
    backupCount: ${logging.rotating_backups}
    encoding: utf-8
    formatter: precise
root:
  level: ${logging.level}
  handlers: [console, file]
disable_existing_loggers: false
