# W&B logging override
version: 1
disable_existing_loggers: false

handlers:
  wandb:
    class: logging.StreamHandler
    level: INFO
    formatter: spectramind_formatter
    stream: ext://sys.stdout

root:
  handlers: [console, file, jsonl, wandb]
