model:
  decoders:
    sigma:
      type: "flow"
      hidden_dim: 256
      out_bins: 283
      min_sigma: 1.0e-4
      max_sigma: 10.0
      flow:
        type: "maf"
        n_blocks: 4
        hidden: 128
        act: "relu"
