# Verbose exports for diagnostics dashboard & CI self-test visibility

model:
  decoders:
    sigma_head:
      logging:
        export_sigma_hist: true
        export_calibration_plots: true
        export_per_bin_csv: true
      fusion:
        export_attention_weights: true
      calibration:
        enable: true
        method: "temperature"
        temperature:
          init_t: 1.0
          learn_t: true
