# Deep ensemble policy for Ïƒ fusion
# Assumes multiple trained heads or checkpoints available.

model:
  decoders:
    sigma_head:
      kind: "ensemble"
      ensemble:
        members: 5                  # number of heads/models
        reduce: "var"               # ["var","mean","median","quantile"]
        jackknife_plus: false
        diversity_weight: 0.0       # optional diversity regularization at train time
      in_features: 256
      hidden_features: 256
      num_layers: 3
      dropout: 0.05
      activation: "silu"
      init: "kaiming_uniform"
      output:
        min_sigma: 1.0e-05
        max_sigma: 0.8
        clamp_strategy: "softplus"
      fusion:
        enable_attention_fuse: false
        symbolic_overlay_weight: 0.0
      calibration:
        enable: true
        method: "corel"
        corel:
          enabled: true
          ckpt: null
          binwise: true
          graph:
            use_edge_features: true
            edge_types: ["distance","molecule","detector_region"]
          training:
            epochs: 8
            lr: 1.0e-3
            weight_decay: 1.0e-4
            batch_size: 64
            coverage_target: 0.6827
            coverage_tolerance: 0.015
