model:
  decoders:
    sigma:
      type: "flow"
      hidden_dim: 320
      out_bins: 283
      min_sigma: 5.0e-5
      max_sigma: 12.0
      flow:
        type: "realnvp"
        n_blocks: 6
        hidden: 160
        act: "silu"
