# Kaggle/runtime-lean overrides for the 9-hour guardrail
# Use simpler head + temperature scaling; disable heavy exports.

model:
  decoders:
    sigma_head:
      kind: "gaussian"
      in_features: 256
      hidden_features: 192
      num_layers: 2
      dropout: 0.05
      activation: "relu"
      init: "kaiming_uniform"
      output:
        min_sigma: 1.0e-05
        max_sigma: 0.6
        clamp_strategy: "softplus"
      fusion:
        enable_attention_fuse: false
        symbolic_overlay_weight: 0.0
      logging:
        export_sigma_hist: false
        export_calibration_plots: false
        export_per_bin_csv: false
      calibration:
        enable: true
        method: "temperature"
        temperature:
          init_t: 1.0
          learn_t: true
