# Leaderboard-oriented Ïƒ config: stable, well-calibrated, mild fusion

model:
  decoders:
    sigma_head:
      kind: "flow"
      in_features: 256
      hidden_features: 256
      num_layers: 4
      dropout: 0.10
      activation: "gelu"
      init: "xavier_uniform"
      output:
        min_sigma: 1.0e-05
        max_sigma: 0.7
        clamp_strategy: "softplus"
      fusion:
        enable_attention_fuse: true
        attention_heads: 4
        attention_dropout: 0.10
        export_attention_weights: false
        symbolic_overlay_weight: 0.10
      flow:
        type: "maf"
        num_transforms: 5
        context_dim: 256
        hidden_features: 256
        num_blocks_per_transform: 2
        tail_bound: 3.0
        batch_norm: true
      calibration:
        enable: true
        method: "corel"
        corel:
          enabled: true
          ckpt: null
          binwise: true
          graph:
            use_edge_features: true
            edge_types: ["distance","molecule","detector_region"]
          training:
            epochs: 10
            lr: 1.0e-3
            weight_decay: 1.0e-4
            batch_size: 64
            coverage_target: 0.6827
            coverage_tolerance: 0.01
