# Quantile head: learns lower/upper quantiles; Ïƒ inferred from spread

model:
  decoders:
    sigma_head:
      kind: "quantile"
      in_features: 256
      hidden_features: 256
      num_layers: 3
      dropout: 0.05
      activation: "relu"
      init: "xavier_uniform"
      quantile:
        q_low: 0.159
        q_high: 0.841
        huber_delta: 0.0          # 0 = pure pinball; >0 = Huberized
      output:
        min_sigma: 1.0e-05
        max_sigma: 0.7
        clamp_strategy: "hard"
      fusion:
        enable_attention_fuse: false
        symbolic_overlay_weight: 0.0
      calibration:
        enable: true
        method: "temperature"
        temperature:
          init_t: 1.0
          learn_t: true
