# Aperture photometry (FGS1) and spectral bin photometry (AIRS)

steps:
  photometry:
    enable: true
    mode: "aperture"                # [aperture|spectral_bins]
    aperture:
      radius_px: 4.0
      annulus_inner_px: 6.0
      annulus_outer_px: 10.0
    centroid:
      enable: true
      method: "gaussian"
    spectral_bins:
      bin_edges_path: "${calib.paths.root}/refs/spectral/bin_edges_283.npy"
      weighting: "variance"         # [uniform|variance]
    normalization:
      enable: false                 # handled in normalization step

