# Physics-grounded constraints
symbolic:
  rules:
    - id: phys_nonneg
      description: "Transmission spectra absorption ≥ 0 in all bins"
      type: "inequality"
      expr: "mu >= 0.0"
      weight: 0.05

    - id: phys_smooth_fft
      description: "Penalize high-frequency power spikes in μ spectrum"
      type: "fft_band_power"
      band: "high"
      target: "low"
      weight: 0.10

    - id: phys_asymmetry
      description: "Reduce unrealistic left/right asymmetry around major features"
      type: "window_asymmetry"
      windows: [[20,40],[120,150],[200,240]]
      weight: 0.02
