# Molecule override — Methane (CH4) emphasis
molecule:
  id: MOL-CH4-001
  name: "Methane"
  formula: "CH4"
  bands_um:
    - [2.1, 2.5]
    - [3.1, 3.6]
    - [7.3, 7.8]
  overrides:
    symbolic_constraints:
      molecular_coherence_weight: 1.35
      smoothness_weight: 0.9
      nonnegativity_weight: 1.0
    calibration:
      corel_enabled: true
      temperature_scaling: 0.98
    uncertainty:
      band_sigma_scale: 0.9
      sigma_floor: 0.02
  notes: "CH4 prominent around 3.3 μm; permit narrower features by easing smoothness slightly."
metadata:
  author: "SpectraMind Architect"
  created: "2025-08-14"
  schema_version: "1.0"
