# configs/profiles/default.yaml
# Balanced default profile for research & testing; reproducible by default.

defaults:
  - override /model: v50
  - override /calibration/steps: standard
  - override /diagnostics: basic
  - override /logging: standard
  - override /symbolic/profiles: default

reproducibility:
  seed: 42
  deterministic: true
