calibration:
  enabled: true
  method: "temperature_scaling"
  temperature: 1.0
  search:
    enabled: true
    grid: [0.5, 0.75, 1.0, 1.25, 1.5]
    metric: "nll"                   # optimize negative log-likelihood
