# Minimal Hydra job logging configuration exposing a SpectraMind JSONL handler
version: 1
formatters:
  simple:
    format: "%(message)s"
handlers:
  spectramind_jsonl:
    class: logging.FileHandler
    level: INFO
    formatter: simple
    filename: logs/events.jsonl
root:
  level: INFO
  handlers: [spectramind_jsonl]
