# hydra entry config: wires groups + symbolic active profile
defaults:
  - profiles: active
  - paths: default
  - logging: default
  - tracking: off
  - scheduler: none
  - runtime: defaults
  - _self_

# universal knobs available to any module
seed: 42
run:
  name: ${now:%Y%m%d_%H%M%S}_${profiles.name}
  mode: ${profiles.mode}   # dev|prod|ci|hpc|cloud
  profile: ${profiles.name}
  # hydra runtime
  workdir: ${paths.run_dir}/${run.name}
  outputs: ${paths.outputs_dir}/${run.name}

# attach logging choices
logging:
  console_level: INFO
  file_level: INFO
  jsonl_level: INFO
