# Hydra Basic Sweeper (Grid/Cartesian expansion over discrete choices)
# Use for deterministic small sweeps and debugging.
# Usage:
# python -m spectramind.cli.spectramind train -m hydra/sweeper=basic

defaults:
  - override /hydra/sweeper: basic

hydra:
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
