# Hydra Optuna Sweeper (CMA-ES Sampler) for SpectraMind V50
# CMA-ES can perform well on continuous, smooth landscapes typical of physics-driven objectives.
# Usage:
# python -m spectramind.cli.spectramind train -m hydra/sweeper=optuna_cmaes
# Recommended:
# Use fewer, more impactful continuous parameters; keep categorical space small.

defaults:
  - override /hydra/sweeper: optuna

hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    direction: minimize
    study_name: spectramind_v50_optuna_cmaes
    storage: null
    n_trials: 80
    n_jobs: 1
    sampler:
      _target_: optuna.samplers.CmaEsSampler
      seed: 42
      restart_strategy: ipop
      sigma0: 0.2
    pruner:
      _target_: optuna.pruners.NopPruner
    params:
      training.lr: tag(log, interval(1e-5, 3e-3))
      training.weight_decay: tag(log, interval(1e-6, 1e-3))
      model.dropout: interval(0.0, 0.35)
      model.encoder_dim: choice(384, 512, 640, 768)
      loss.symbolic.weight: tag(log, interval(1e-4, 5e-2))
      loss.smoothness_l2.weight: tag(log, interval(1e-5, 5e-3))
      calib.temperature_init: interval(0.8, 2.5)
