# Hydra Optuna Sweeper (Random Sampler) for SpectraMind V50
# A pure random sampler can help broad exploration or quick smoke tests for search spaces.
# Usage:
# python -m spectramind.cli.spectramind train -m hydra/sweeper=optuna_random

defaults:
  - override /hydra/sweeper: optuna

hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    direction: minimize
    study_name: spectramind_v50_optuna_random
    storage: null
    n_trials: 48
    n_jobs: 1
    sampler:
      _target_: optuna.samplers.RandomSampler
      seed: 42
    pruner:
      _target_: optuna.pruners.NopPruner
    params:
      optimizer.name: choice(adamw, lion)
      training.lr: tag(log, interval(5e-6, 1e-2))
      training.weight_decay: tag(log, interval(1e-7, 1e-3))
      training.batch_size: choice(16, 32, 48, 64)
      model.encoder_dim: choice(256, 384, 512, 640, 768)
      model.dropout: interval(0.0, 0.5)
