# Hydra's own internal logger (separate from the job logger)

version: 1
formatters:
  hydra:
    format: "%(asctime)s %(levelname)s [HYDRA] %(name)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    formatter: hydra
    level: INFO
    stream: ext://sys.stdout
root:
  level: INFO
  handlers: [console]
disable_existing_loggers: false
