# Hydra config for fusion module
_target_: spectramind.models.fusion.ConcatMLPFusion
dim: 256
dropout: 0.05
norm: layernorm
jit_safe: true
export_taps: false
export_attn: false
export_gate: false
d_fgs1: 256
d_airs: 256
strict_check: true
