# configs/symbolic/profiles/default.yaml

symbolic:
  enable: true
  rules:
    - smoothness
    - nonnegativity
    - entropy
  weights:
    smoothness: 0.7
    nonnegativity: 0.7
    entropy: 0.7
  enforce_hard: false
  violation_penalty: 1.0
