symbolic:
  profile:
    name: "leaderboard"
    description: "Leaderboard-focused profile: stronger physical priors, tighter caps, curated exports."
    normalize: true
    mode: "soft"
    export_detail: "summary"
    toggles:
      export_fft_power: false
      export_alignment: true
      export_per_molecule: true
      export_violation_maps: true
    caps:
      per_rule_cap: 6.0
    weights:
      smoothness: 1.10
      nonnegativity: 1.30
      fft_bandlimit: 0.45
      asymmetry: 0.30
      photonic_alignment: 0.60
      molecule_coherence: 0.50
      transit_shape_consistency: 0.40
      quantile_consistency: 0.30
