# @package _group_
# Calibration diagnostics config

methods: ["temperature_scaling", "corel"]
evaluate_coverage: true
coverage_quantiles: [0.5, 0.8, 0.9]
symbolic_region_analysis: true
export_formats: ["png", "csv", "json"]
