# configs/diagnostics/explain.yaml

diagnostics:
  enable_fft: true
  enable_shap: true
  enable_symbolic_overlay: true
  enable_dashboard: true
  enable_interactive_html: true
  overlays: ["shap_bars", "umap", "tsne"]
  fusion_overlays: ["shap", "entropy"]
  molecular_templates: []
  molecular_focus: []
  enable_cosmology_context: false
