# @package _group_
# FFT + spectral diagnostics

apply_to: "mu"             # "mu", "sigma"
include_autocorr: true
molecule_overlay: ["H2O", "CH4", "CO2"]
export_formats: ["png", "csv", "json"]
highlight_clusters: true
