# =====================================================================
# SpectraMind V50 — FFT Diagnostics Configuration
# ---------------------------------------------------------------------
# Purpose:
#   Perform Fourier analysis on μ spectra for each planet/bin, compute
#   power spectra, detect periodicities, and overlay symbolic/SHAP maps.
# Inputs:
#   - Predicted μ spectra (CSV or NumPy)
#   - Optional σ, GLL metrics
# Outputs:
#   - Power spectra PNG/HTML
#   - Peak frequency CSV
#   - Overlay plots with molecule region annotations
# =====================================================================

defaults:
  - base

diagnostics:
  fft:
    window_function: "hann"
    normalize: true
    detrend: true
    min_frequency: 0.0
    max_frequency: 0.5
    peak_detection:
      enabled: true
      prominence: 0.05
      min_distance_bins: 3
    overlay_symbolic: true
    overlay_shap: true
