# ===================================================================
# Diagnostics — Leaderboard config
# ===================================================================

diagnostics:
  leaderboard:
    html_out: runs/leaderboard/ablation_leaderboard.html
    md_out: runs/leaderboard/ablation_leaderboard.md
    top_n: 20
    include_zip_export: true

