# @package _group_
# SHAP diagnostics configuration

compute_airs: true         # Run SHAP on AIRS spectra
compute_fgs1: true         # Run SHAP on FGS1 light curves
top_k_bins: 15             # Highlight top-K most influential bins
overlay_symbolic: true     # Overlay symbolic rule violations
export_formats: ["png", "html", "json"]
html_interactive: true     # Produce interactive Plotly figures
