# @package _group_
# Symbolic rule violation diagnostics configuration

rank_rules: true           # Rank rules by mean violation score
top_rules: 20              # Number of top rules to display
output_matrix: true        # Save planet × rule violation matrix
export_formats: ["csv", "json", "html"]
overlay_shap: true         # If true, merge with SHAP overlays
