# @package _group_
# UMAP projection diagnostics

latent_source: "fusion"    # "fusion", "airs", "fgs1"
dimensions: 2              # 2 or 3
n_neighbors: 15
min_dist: 0.1
color_by: "symbolic_cluster"  # Options: symbolic_cluster, gll_score, shap_entropy
size_by: "confidence"
dedupe: true
html_output: "umap_plot.html"
