# Hot Jupiter symbolic profile: emphasize strong molecular bands, stabilize systematics at high T_eq.

symbolic:
  loss:
    weights:
      smooth_l2_mu: 0.8
      nonneg_mu: 0.4
      fft_band_limit: 0.2
      asymmetry_mu: 0.15
      photonic_alignment: 0.8
      molecule_region_coherence: 1.2
      symbol_coverage_penalty: 0.05
    options:
      fft:
        window: "hann"
        max_rel_band: 0.30
      molecule_sets:
        include: ["H2O","CO2","CH4","CO","NH3","HCN","C2H2"]
      photonic:
        use_fgs1_phase_anchor: true
        jitter_robust: true
  sigma:
    calibration:
      temperature_scaling: 0.9
      corel_weight: 0.7
      conformal_coverage_target: 0.75
      per_bin: true
  guards:
    ood:
      enable_entropy_tripwire: true
      entropy_threshold: 1.10
      zscore_threshold: 2.8
      switch_to_profile: "ood_guardrails"
  reporting:
    export_masks: true
    export_rule_scores: true
