# Warm Neptune profile: moderate bands, stronger smoothness to fight low SNR and feature crowding.

symbolic:
  loss:
    weights:
      smooth_l2_mu: 1.3
      nonneg_mu: 0.6
      fft_band_limit: 0.27
      asymmetry_mu: 0.18
      photonic_alignment: 0.7
      molecule_region_coherence: 1.0
      symbol_coverage_penalty: 0.08
    options:
      fft:
        window: "hann"
        max_rel_band: 0.33
      molecule_sets:
        include: ["H2O","CO2","CH4","NH3"]
      photonic:
        use_fgs1_phase_anchor: true
        jitter_robust: true
  sigma:
    calibration:
      temperature_scaling: 1.05
      corel_weight: 0.6
      conformal_coverage_target: 0.70
      per_bin: true
  guards:
    ood:
      enable_entropy_tripwire: true
      entropy_threshold: 1.20
      zscore_threshold: 3.0
      switch_to_profile: "ood_guardrails"
  reporting:
    export_masks: true
    export_rule_scores: true
