# Ablation / sweep space for FGS1 encoder
# Use with: spectramind ablate -m model.encoders.fgs1_mamba=@fgs1_mamba/ablation ...

ablate:
  enable: true
  max_runs: 24
  top_n: 5
  search_space:
    model.encoders.fgs1_mamba.d_model: [128, 192, 256, 320]
    model.encoders.fgs1_mamba.d_state: [32, 48, 64, 96]
    model.encoders.fgs1_mamba.n_layers: [4, 6, 8, 10]
    model.encoders.fgs1_mamba.bidirectional: [true, false]
    model.encoders.fgs1_mamba.dropout: [0.05, 0.10, 0.12]
    model.encoders.fgs1_mamba.layer_norm: ["rms", "layernorm"]
    # fusion interplay (if you sweep jointly)
    model.fusion.kind: ["concat", "gated"]
  logging:
    level: "INFO"
  export:
    md: "outputs/ablate/fgs1_mamba_leaderboard.md"
    html: "outputs/ablate/fgs1_mamba_leaderboard.html"
    zip_top_n: true
    zip_dir: "outputs/ablate/topn_bundles"