model:
  encoders:
    fgs1_mamba:
      enabled: true
      in_features: 6
      d_model: 256
      d_state: 64
      d_conv: 4
      expand: 2
      n_layers: 8
      bidirectional: true
      dropout: 0.10
      layer_norm: "rms"
      proj_out: 256
      export_step_latents: false
