# FGS1 Mamba SSM encoder
type: mamba
input_dim: 4          # flux + jitter_x + jitter_y + centroid (or other features)
latent_dim: 256
n_layers: 6
bidirectional: true
dropout: 0.1
residual: true
amp: true              # mixed precision