# Mid-size preset for single-GPU development
model:
  encoders:
    fgs1_mamba:
      d_model: 192
      d_state: 48
      d_conv: 4
      expand: 2
      n_layers: 6
      bidirectional: true
      dropout: 0.10
      layer_norm: "rms"
      proj_out: 192
      export_step_latents: false