# Unified model composition
model:
  encoders:
    fgs1_mamba:
      enabled: true
      in_features: 6              # [flux, t_norm, cx, cy, jx, jy]
      d_model: 256
      d_state: 64
      d_conv: 4
      expand: 2
      n_layers: 8
      bidirectional: true
      dropout: 0.10
      layer_norm: "rms"           # "layernorm" | "rms"
      proj_out: 256
      export_step_latents: false

    airs_gnn:
      enabled: true
      in_features: 1
      hidden_dim: 256
      num_layers: 4
      gnn_type: "gat"             # "gat" | "rgcn"
      heads: 4
      edge_features: ["wavelength_proximity","molecule_region","detector_region"]
      residual: true
      dropout: 0.10
      readout: "mean"             # "mean" | "sum" | "attn"

  fusion:
    strategy: "concat"            # "concat" | "gated" | "cross_attn"
    out_dim: 256
    norm: "layernorm"
    dropout: 0.05

  decoders:
    mu:
      type: "multi_scale"
      hidden_dim: 256
      out_bins: 283
      n_scales: 3
      scale_factors: [1, 2, 4]
      activation: "silu"
      smoothing_penalty: 0.001

    sigma:
      type: "flow"
      hidden_dim: 256
      out_bins: 283
      min_sigma: 1.0e-4
      max_sigma: 10.0
      flow:
        type: "maf"               # "maf" | "realnvp"
        n_blocks: 4
        hidden: 128
        act: "relu"

loss:
  objective: "gll"                # Gaussian log-likelihood
  weights:
    gll: 1.0
    smooth_fft: 0.05
    asymmetry: 0.02
    symbolic: 0.20

uncertainty:
  calibration_head: false
  temperature_init: 1.0
