# SpectraMind V50 — Default Model Config

# Root defaults (Hydra composition)
defaults:
  - fgs1_mamba: default
  - airs_gat: default
  - fusion: concat_mlp
  - mu_decoder: multi_scale
  - sigma_head: flow
  - symbolic: default
  - _self_

# Global latent dims
latent_dim: 256

# Dropout applied across encoders/decoders
dropout: 0.1

# TorchScript-safe mode for inference
torchscript: true