# @package model.fgs1_mamba
# Configuration for FGS1 Mamba encoder (long sequence modeling for light curves)

_target_: spectramind.models.fgs1_mamba.FGS1MambaEncoder

seq_len: 135000       # full lightcurve length
patch_size: 128       # downsampling factor
hidden_dim: 256       # embedding size
depth: 12             # number of Mamba layers
dropout: 0.1
use_snr_dropout: true # enable SNR-aware dropout for calibration
symbolic_overlays: true # log symbolic violations on latent
