# @package model.fgs1_mamba
# Configuration for FGS1 Mamba encoder (long sequence modeling for light curves)

_target_: spectramind.models.fgs1_mamba.FGS1MambaEncoder

input_dim: 32
hidden_dim: 128
depth: 12
dropout: 0.1

