# @package model.multi_scale_decoder
# Multi-scale spectral decoder for Î¼ output (mean prediction)

_target_: spectramind.models.multi_scale_decoder.MultiScaleDecoder

hidden_dim: 128
output_bins: 283

