# @package model.spectral_corel
# SpectralCOREL calibration GNN with temporal bin correlations

_target_: spectramind.models.spectral_corel.SpectralCOREL

input_dim: 283
hidden_dim: 128
output_dim: 283

