# Model group: v50

# Neuro-symbolic, physics-aware defaults aligned with mission specs

fgs1_encoder: MambaSSM
airs_encoder: GATConv
decoder_mu: MultiScaleDecoder
decoder_sigma: FlowUncertaintyHead
latent_dim: 512

symbolic_loss_weights:
  smoothness: 0.25
  nonnegativity: 0.10
  molecular_coherence: 0.15
  asymmetry: 0.05
  photonic_alignment: 0.10
  fft_spectral: 0.10

use_quantile_decoder: false
use_diffusion_decoder: false

conformal_corel: true
corel_coverage: 0.90

airs_edge_features: [d_lambda, molecule, region]
airs_posenc: fourier
