# Competition override — BALANCED mode
competition:
  id: COMP-BAL-001
  name: "Competition Balanced"
  description: "Balanced accuracy/speed/robustness for daily runs"
  mode: balanced
  guards:
    determinism:
      seed: 2025
      cudnn_deterministic: true
      cudnn_benchmark: false
      allow_tf32: true
      amp: "bf16"
    runtime:
      max_hours: 9.0
      num_workers: 4
      prefetch_factor: 4
      pin_memory: true
      batch_size_infer: 12
      batch_size_train: 24
    memory:
      gradient_checkpointing: true
      activation_offload: false
  overrides:
    symbolic_constraints:
      nonnegativity_weight: 1.1
      smoothness_weight: 1.0
      molecular_coherence_weight: 1.1
    calibration:
      corel_enabled: true
      temperature_scaling: 0.98
    uncertainty:
      sigma_floor: 0.025
metadata:
  author: "SpectraMind Architect"
  created: "2025-08-14"
  schema_version: "1.0"
