# configs/symbolic/overrides/competition/corel.yaml

# COREL GNN backbone configuration — edge-feature aware, temporal correlation modeling.

corel:
  gnn:
    backend: "GAT"      # ["GAT", "RGCN", "NNConv", "MPNN"]
    heads: 4
    layers: 4
    hidden_dim: 128
    dropout: 0.05
    residual: true
  edge_features:
    use_distance: true
    use_molecule_type: true
    use_detector_region: true
    normalize: true
  positional_encoding:
    type: "fourier"   # ["none", "sinusoidal", "fourier"]
    dim: 16
    scale: 1.0
  training:
    batch_size: 32
    lr: 3.0e-4
    epochs: 8
    mixed_precision: true
    checkpoint_every: 2
  explainability:
    export_attention_weights: true
    coverage_heatmaps: true
    region_breakdowns: true
  outputs:
    per_bin_csv: "runs/corel/per_bin_sigma.csv"
    heatmap_png: "runs/corel/coverage_heatmap.png"
