# SpectraMind V50 — AIRS spectral GNN encoder (physics-informed GAT)
# Binds to: src/spectramind/models/airs_gnn.py::AIRSGNNEncoder
spectramind:
  models:
    airs_gnn:
      class: "spectramind.models.airs_gnn.AIRSGNNEncoder"
      params:
        in_features: 256
        gnn_type: "gat"
        num_layers: 4
        hidden_dim: 256
        heads: 4
        dropout: 0.10
        edge_features: ["delta_lambda", "mol_tag_i", "mol_tag_j", "seam_flag"]
        use_edge_attr: true
        export_attention_weights: true
        torchscript_safe: true
