# SpectraMind V50 — FGS1 Mamba SSM encoder (temporal, long-sequence)
# Binds to: src/spectramind/models/fgs1_mamba.py::FGS1MambaEncoder
spectramind:
  models:
    fgs1_mamba:
      class: "spectramind.models.fgs1_mamba.FGS1MambaEncoder"
      params:
        in_features: 6
        d_model: 256
        d_state: 64
        d_conv: 4
        expand: 2
        n_layers: 8
        bidirectional: true
        dropout: 0.10
        layer_norm: "rms"
        proj_out: 256
        export_step_latents: false
        amp: true
        torchscript_safe: true
