# SpectraMind V50 — Latent fusion between FGS1 & AIRS encoders
# Binds to: src/spectramind/models/fusion.py::FusionBlock
spectramind:
  models:
    fusion:
      class: "spectramind.models.fusion.FusionBlock"
      params:
        type: "concat_mlp"
        hidden_dim: 256
        dropout: 0.05
        gate_init_bias: 0.0
        symbolic_aware: true
