# SpectraMind V50 — Multi-scale μ decoder (coarse→mid→fine with skips)
# Binds to: src/spectramind/models/multi_scale_decoder.py::MultiScaleMuDecoder
spectramind:
  models:
    multi_scale_decoder:
      class: "spectramind.models.multi_scale_decoder.MultiScaleMuDecoder"
      params:
        base_dim: 256
        scales: ["coarse","mid","fine"]
        skip_connections: true
        activation: "gelu"
        dropout: 0.05
        output_bins: 283
        symbolic_aware: true
