# @package _group_
# Runtime config for HPC clusters (Slurm, PBS, etc.).

defaults:
  - default

runtime:
  name: hpc
  description: "High-performance cluster runtime."
  device: "cuda"
  num_workers: 16

  distributed:
    enabled: true
    backend: "nccl"
    world_size: ${oc.env:WORLD_SIZE,8}
    rank: ${oc.env:RANK,0}

