# configs/model/mu_decoder/base.yaml
model:
  decoders:
    mu_decoder:
      enabled: true
      type: "multi_scale"
      in_dim: 256
      hidden_dims: [512, 256]
      scales:
        - name: "coarse"
          bins: 71
          loss_weight: 0.25
        - name: "mid"
          bins: 142
          loss_weight: 0.25
        - name: "fine"
          bins: 283
          loss_weight: 0.50
      activation: "gelu"
      dropout: 0.1
      skip_fusion: true
      norm: "layernorm"
      output_activation: null
      init: "xavier_uniform"
      export_attention: false
      aux_losses: true
