model:
  decoders:
    mu:
      type: "multi_scale"
      hidden_dim: 320
      out_bins: 283
      n_scales: 4
      scale_factors: [1,2,4,8]
      activation: "gelu"
      smoothing_penalty: 0.0015
