# Quantile-Aux μ decoder — adds auxiliary quantile heads during training
#
# Hydra path: model/mu_decoder/quantile_aux
#
# Compose via: defaults: [ model/mu_decoder@model.decoders.mu_decoder: quantile_aux ]
#
# Use when you want pinball-loss quantiles to stabilize μ tails; disable at inference.

model:
  decoders:
    mu_decoder:
      enabled: true

      in_dim: 256
      out_bins: 283

      hidden:
        dims: [512, 512]
        activation: "silu"
        dropout: 0.10
        normalization: "layernorm"
        residual: true

      head:
        type: "linear"
        final_activation: "none"
        init: "xavier_uniform"

      # Main μ loss remains GLL (paired with σ head elsewhere).
      loss:
        type: "gll"
        weight: 1.0
        smooth:
          l2_weight: 0.010
          window: 5
        fft_smooth:
          weight: 0.000
          max_freq: null
        asymmetry:
          weight: 0.000
        nonneg:
          weight: 0.000

      # Auxiliary quantile heads:
      quantile_aux:
        enabled: true
        quantiles: [0.05, 0.50, 0.95]  # median + tails
        weight: 0.30                    # contribution of pinball loss to total
        head:
          shared_trunk: true            # reuse hidden trunk for efficiency
          dims: [256]                   # optional extra head layers
          activation: "silu"
          dropout: 0.10
          normalization: "layernorm"

      multiscale:
        enabled: false
      moe:
        enabled: false

      export:
        save_intermediate: false
        save_dir: "artifacts/mu_decoder_quantile"
      log:
        level: "INFO"
        include_shapes: true
