# configs/model/sigma_decoder/base.yaml
model:
  decoders:
    sigma_decoder:
      enabled: true
      type: "flow_uncertainty"     # [flow_uncertainty, quantile]
      in_dim: 256
      hidden_dims: [256, 128]
      activation: "gelu"
      dropout: 0.1
      output_activation: "softplus"
      sigma_min: 1e-4
      norm: "layernorm"
      init: "xavier_uniform"
      export_attention: false
      quantiles: null              # e.g., [0.1, 0.5, 0.9] if using quantile head
      monotonicity_loss: false     # Set true if quantiles are predicted
