# Ensemble sigma decoder: convex combination of flow and quantile-derived Ïƒ.
# Requires both heads active in model code or sequential calls in pipeline.
model:
  sigma_decoder:
    name: ensemble
    enabled: true
    # Weights sum to 1.0; set flow_w=1.0 for pure flow, 0.0 for pure quantile.
    blend:
      flow_w: 0.7
      quantile_w: 0.3
    # Floors at the end (ppm)
    sigma_min_ppm:
      fgs1: 1.0
      airs: 10.0
