# Reproducibility exports for Ïƒ-related artifacts.
export:
  artifacts:
    write_per_bin_csv: true
    per_bin_csv_path: "outputs/diagnostics/per_bin_sigma_coverage.csv"
    write_summary_json: true
    summary_json_path: "outputs/diagnostics/calibration_summary.json"
    write_html_report: true
    html_report_path: "outputs/diagnostics/calibration_report.html"
  provenance:
    include_git_sha: true
    include_config_hash: true
    include_timestamp: true
