# =================================================================================================
# File: configs/symbolic/overrides/regions/kaggle.yaml
# SpectraMind V50 — Regions Override (Kaggle/CI)
# --------------------------------------------------------------------------------
# Purpose:
# Turn on strict schema, ensure JSON masks, and route exports into submission bundle area.
# =================================================================================================
symbolic:
  regions:
    enabled: true
    packs:
      base: configs/symbolic/regions/regions_base.yaml
      molecular: configs/symbolic/regions/molecular_regions.yaml
      astrophysical: configs/symbolic/regions/astrophysical_regions.yaml
      telescope: configs/symbolic/regions/telescope_regions.yaml
      challenge: configs/symbolic/regions/challenge_regions.yaml

    gates:
      use_astrophysical: true
      use_molecular: true
      use_telescope: true
      use_challenge: true

    weights:
      molecular_fingerprint: 1.2
      continuum_reference: 1.1
      near_ir_baseline: 1.1
      scattering_reference: 1.1
      thermal_baseline: 1.1
      mixed_molecule_test: 1.3

    validation:
      enforce_schema: true
      schema_path: configs/symbolic/_schemas/symbolic_region.schema.json
      on_violation: "error"

    exports:
      write_masks_csv: false
      write_masks_json: true
      export_dir: submission_bundle/symbolic/regions
