# =================================================================================================
# File: configs/symbolic/overrides/regions/local.yaml
# SpectraMind V50 — Regions Override (Local Dev Convenience)
# --------------------------------------------------------------------------------
# Purpose:
# Lightweight exports and permissive warnings for fast iteration on a laptop or dev VM.
# =================================================================================================
symbolic:
  regions:
    enabled: true
    packs:
      base: configs/symbolic/regions/regions_base.yaml
      molecular: configs/symbolic/regions/molecular_regions.yaml
      astrophysical: configs/symbolic/regions/astrophysical_regions.yaml
      telescope: configs/symbolic/regions/telescope_regions.yaml
      challenge: configs/symbolic/regions/challenge_regions.yaml

    gates:
      use_astrophysical: true
      use_molecular: true
      use_telescope: true
      use_challenge: false

    weights:
      molecular_fingerprint: 1.0
      continuum_reference: 1.0
      near_ir_baseline: 1.0
      scattering_reference: 1.0
      thermal_baseline: 1.0
      mixed_molecule_test: 1.0

    validation:
      enforce_schema: true
      schema_path: configs/symbolic/_schemas/symbolic_region.schema.json
      on_violation: "warn"

    exports:
      write_masks_csv: false
      write_masks_json: true
      export_dir: artifacts/symbolic/regions_local
