# =================================================================================================
# File: configs/symbolic/overrides/regions/telescope.yaml
# SpectraMind V50 — Regions Override (Telescope/Instrument)
# --------------------------------------------------------------------------------
# Purpose:
# Focus on bandpass sanity, channel boundary effects, and cross-channel continuity.
# =================================================================================================
symbolic:
  regions:
    enabled: true
    packs:
      base: configs/symbolic/regions/regions_base.yaml
      molecular: configs/symbolic/regions/molecular_regions.yaml
      astrophysical: configs/symbolic/regions/astrophysical_regions.yaml
      telescope: configs/symbolic/regions/telescope_regions.yaml
      challenge: configs/symbolic/regions/challenge_regions.yaml

    gates:
      use_astrophysical: true
      use_molecular: true
      use_telescope: true
      use_challenge: false

    weights:
      molecular_fingerprint: 1.1
      continuum_reference: 1.4
      near_ir_baseline: 1.4
      scattering_reference: 1.2
      thermal_baseline: 1.2
      mixed_molecule_test: 0.8

    validation:
      enforce_schema: true
      schema_path: configs/symbolic/_schemas/symbolic_region.schema.json
      on_violation: "warn"

    exports:
      write_masks_csv: true
      write_masks_json: true
      export_dir: artifacts/symbolic/regions_telescope
