meta:
  profile: strict
  version: "1.0.0"
  description: Stricter/safer weighting; reduces false positives.

weights:
  spectral_consistency: 1.3
  line_id_confidence: 1.1
  residual_penalty: 1.6
  prior_chemistry: 0.9
  instrument_systematics: 0.8
  nan_guard: 20.0
  outlier_guard: 10.0

constraints:
  min: -8.0
  max:  8.0
  clip: true
