# Root Hydra configuration for SpectraMind V50.

# Compose with: model/defaults, training/default, data/ariel, logging/default, paths/config

# This file is the single entry-point for CLI tools: --config-name config_v50

defaults:
  - model: defaults
  - training: default
  - data: ariel
  - logging: default
  - paths: config
  - hydra/job_logging: rich
  - hydra/hydra_logging: rich

# Freeform extras for experiment tagging; preserved in Config.extras
extras:
  experiment_tag: "v50_default"
  purpose: "neurips_2025_ariel_data_challenge"

# Optional global overrides (rarely used; prefer group files)
hydra:
  run:
    dir: ${paths.outputs.runs_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}${oc.env:USER,unknown}${hydra.job.name}_${hydra.job.num}
  sweep:
    dir: ${paths.outputs.runs_dir}/multirun/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra.job.num}_${hydra.runtime.choices}
