# SpectraMind V50 – Hydra/OmegaConf config (calibration-focused)
# This file provides minimal defaults so the calibration CLI runs immediately.

paths:
  raw_data: data/raw
  calibrated_output: outputs/calibrated

calibration_pipeline:
  photometry:
    random_seed: 1337
    planets: ["planet_001", "planet_002", "planet_003", "planet_004"]
    samples_per_planet: 1024
  calibration:
    default_sigma: 0.02
    corel:
      coverage_quantile: 0.9
      min_sigma: 0.0001
  checker:
    z_hist_bins: 60
