# Master root config for SpectraMind V50 (Hydra)
# Registers the `profiles` group and makes its fields available globally.

defaults:
  - hydra/job_logging: default
  - hydra/launcher: basic
  - hydra/sweeper: basic

  # Profiles group: choose the default profile; users can override with profiles=<name>
  - profiles: default

  # Project groups wired to read from the active profile (see their defaults files)
  - logging: default
  - diagnostics: default
  - calibration/steps: default
  - model: default

project:
  name: SpectraMind V50
  mode: standard  # e.g., standard | leaderboard | ci

# Expose the active profile universally
active_profile: ${profiles.profile.name}

reproducibility:
  seed: ${oc.select:profiles.profile.reproducibility.seed,42}
  deterministic: ${oc.select:profiles.profile.reproducibility.deterministic,true}

# Surface symbolic & diagnostics via profile (downstream groups refine this)
symbolic:
  enable: ${profiles.profile.symbolic.enable}
  rules: ${profiles.profile.symbolic.rules}
  weighting: ${profiles.profile.symbolic.weighting}

diagnostics:
  enable_fft: ${oc.select:profiles.profile.diagnostics.enable_fft,false}
  enable_shap: ${oc.select:profiles.profile.diagnostics.enable_shap,false}
  enable_symbolic_overlay: ${oc.select:profiles.profile.diagnostics.enable_symbolic_overlay,false}
  enable_dashboard: ${oc.select:profiles.profile.diagnostics.enable_dashboard,false}
  enable_interactive_html: ${oc.select:profiles.profile.diagnostics.enable_interactive_html,false}
  fusion_overlays: ${oc.select:profiles.profile.diagnostics.fusion_overlays,[]}
  overlays: ${oc.select:profiles.profile.diagnostics.overlays,[]}
  molecular_templates: ${oc.select:profiles.profile.diagnostics.molecular_templates,[]}
  molecular_focus: ${oc.select:profiles.profile.diagnostics.molecular_focus,[]}
  enable_cosmology_context: ${oc.select:profiles.profile.diagnostics.enable_cosmology_context,false}

logging:
  level: INFO
  jsonl_events: true
  file_rotation_mb: 25
  file_keep: 5
