# configs/config_v50.yaml
# Unified Hydra entry config for SpectraMind V50 with logging group registered.

defaults:
  # Select logging backend (switch via CLI: +logging={console,file,jsonl,mlflow})
  - logging: console

  # You likely have many more defaults here (models, data, train, etc.). Keep them below.
  # - model: v50_default
  # - data: ariel_default
  # - train: default

# Example top-level keys; real project will have many more.
project:
  name: SpectraMindV50
  seed: 1234

# The selected logging dictConfig will be available under cfg.logging.
# Your entrypoints can call:
#   from spectramind.logging.apply import install_from_hydra
#   install_from_hydra(cfg)
