# Canonical composition: override with `+group=name` or `group=name` on CLI as needed.
defaults:
  - data: base
  - model: defaults
  - training: base
  - calibration: base
  - diagnostics: defaults
  - runtime: default
  - symbolic: base
  - profiles: default
