# Hydra Basic Launcher — SpectraMind V50
# Built-in Hydra launcher; executes in-process.
# Useful for debugging or environments without plugin launchers.

defaults:
  - override /hydra/launcher: basic

hydra:
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
