# -----------------------------------------------------------------------------
# SLURM cluster launcher using hydra-submitit-launcher
# -----------------------------------------------------------------------------
# Submit parallel/multi-run jobs to a SLURM cluster with GPU resources.
# You can override any field at the CLI (see README.md for examples).
# -----------------------------------------------------------------------------
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher

# Core resources (override as needed)
partition: gpu
gres: gpu:1
cpus_per_task: 8
mem_gb: 32
timeout_min: 600        # 10 hours
max_num_timeout: 1

# Optional extras (uncomment/override at CLI as needed)
# qos: high
# account: your_account
# nodelist: nodeA
# array_parallelism: 4

# Submitit/Hydra metadata
submitit_folder: ${hydra.sweep.dir}/.slurm_submitit
name: spectramind_v50
