# Hydra Submitit Slurm Launcher — SpectraMind V50
# Cluster-ready configuration for scalable sweeps and single runs.
# Requires: hydra-submitit-launcher plugin and Slurm environment.
# Usage:
# python -m spectramind.cli.spectramind train -m hydra/launcher=submitit_slurm hydra/sweeper=optuna_tpe
# Common overrides:
# +hydra.launcher.partition=gpu
# +hydra.launcher.gpus_per_node=1
# +hydra.launcher.cpus_per_task=8
# +hydra.launcher.mem_gb=48
# +hydra.launcher.timeout_min=720

defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
    account: null
    partition: gpu
    qos: null
    gpus_per_node: 1
    tasks_per_node: 1
    cpus_per_task: 8
    mem_gb: 32
    nodes: 1
    timeout_min: 240
    name: ${oc.env:USER,unknown}-smv50-${now:%Y%m%d_%H%M%S}
    signal_delay_s: 120
    max_num_timeout: 0
    array_parallelism: 64
    additional_parameters: {}
    setup: null
    constraint: null
