model:
  encoders:
    airs_gnn:
      enabled: true
      in_features: 1
      hidden_dim: 256
      num_layers: 4
      gnn_type: "gat"
      heads: 4
      residual: true
      dropout: 0.10
      readout: "mean"
      edge_features: ["wavelength_proximity","molecule_region","detector_region"]
