# Large preset — more depth/width & heads; consider runtime budget.

model:
  encoders:
    airs_gnn:
      enabled: true
      backend: "gat"
      hidden_dim: 320
      num_layers: 7
      attn_heads: 6
      attn_dropout: 0.10
      dropout: 0.10
      residual: true
      layer_norm: "rms"
      activation: "silu"
      node_features:
        use: ["stat", "learned"]
        stat_dim: 12
        learned_dim: 48
        fuse: "concat"
        mlp_dim: 192
      diagnostics:
        save_attention_csv: false
        save_graphviz: false
        assert_connected_graph: true
        log_shapes: true
