# Shared physics graph description for AIRS (applies to all backends).
# This file defines:
#  - wavelength adjacency (k-nearest along spectral order)
#  - molecule windows (H2O/CO2/CH4) for coherence edges
#  - detector seam index(es)
#  - which edge features to include

model:
  encoders:
    airs_gnn:
      graph:
        num_nodes: 283                     # AIRS bins
        spectral_order: "increasing"       # bins are ordered by wavelength ascending
        k_adj: 2                           # connect each bin to k neighbors on each side (adjacency)
        include_self_loops: false

        # Detector seams (indices where detector subarrays meet, if any)
        # Use a single integer or list. Set to null if none.
        seam_indices: [142]                # example seam between channels/subarrays; adjust if known

        # Molecule windows (indices are 0-based inclusive ranges)
        # These should reflect approximate band coverage in AIRS-CH0.
        molecules:
          H2O:
            ranges:
              - [30, 60]
              - [190, 230]
          CO2:
            ranges:
              - [95, 120]
              - [240, 270]
          CH4:
            ranges:
              - [140, 170]

        # Edge feature configuration
        edge_features:
          use_delta_lambda: true           # |Δλ| between bins (use bin index distance if λ table absent)
          use_molecule_tags: true          # one-hot or indices for molecule band membership
          use_seam_flag: true              # edge crossing a seam gets flag=1
          encoding:
            type: "learned"                # ["learned", "fourier", "none"]
            dim: 16                        # embedding size if learned/fourier
            num_fourier_feats: 8           # used if type=fourier
          normalize_delta_lambda: true     # scale Δλ to [0,1] by max span

        # Graph sanity checks
        checks:
          enforce_connected: true
          validate_edge_attr_shapes: true

