model:
  encoders:
    airs_gnn:
      enabled: true
      backend: "gat"
      hidden_dim: 160
      num_layers: 4
      attn_heads: 4
      attn_dropout: 0.10
      dropout: 0.10
      residual: true
      layer_norm: "rms"
      activation: "silu"
      node_features:
        use: ["stat", "learned"]
        stat_dim: 8
        learned_dim: 24
        fuse: "concat"
        mlp_dim: 96
      diagnostics:
        assert_connected_graph: true
        log_shapes: true
