# Tiny preset — fast, good for smoke tests and Kaggle runtime budgeting.

model:
  encoders:
    airs_gnn:
      enabled: true
      backend: "gat"
      hidden_dim: 96
      num_layers: 3
      attn_heads: 3
      attn_dropout: 0.10
      dropout: 0.10
      residual: true
      layer_norm: "rms"
      activation: "silu"
      node_features:
        use: ["stat", "learned"]
        stat_dim: 6
        learned_dim: 16
        fuse: "concat"
        mlp_dim: 64
      diagnostics:
        save_attention_csv: false
        save_graphviz: false
        assert_connected_graph: true
        log_shapes: true
