# Lightweight defaults — safe, minimal baseline that passes schema validation.
model:
  encoder: "fgs1_mamba"
  decoder: "multi_scale_decoder"
  params:
    hidden_dim: 256
    dropout: 0.1

training:
  epochs: 10
  batch_size: 32
  lr: 0.001
  optimizer: "adamw"

calibration:
  method: "corel"

diagnostics:
  run_gll: true
  run_fft: true

symbolic:
  enable_constraints: true

env:
  device: "cuda"
