# Base Fusion Config — physics-informed latent fusion between FGS1 Mamba and AIRS GAT
fusion:
  enabled: true
  type: concat+mlp           # options: concat+mlp | cross-attend | gate
  dim: 256                   # latent dimension after fusion
  dropout: 0.1               # dropout applied after fusion layer
  layer_norm: true           # whether to apply LayerNorm after fusion
  residual: true             # whether to add residual connection between encoders and fused output
  amp: true                  # use automatic mixed precision in fusion
  export_attention: false    # export attention maps for diagnostics (only for attention-based fusion)
  export_step_latents: false # export per-step latents for embedding visualizations (UMAP/t-SNE)