# -----------------------------------------------------------------------------
# Fusion: Default Selector (Project-Wide)
# -----------------------------------------------------------------------------
# Include this in your root config defaults to pin the project's default fusion.
# Example in config_v50.yaml:
#   defaults:
#     - model/fusion: default
# -----------------------------------------------------------------------------

defaults:
  - concat