# Gated Fusion Config — learned scalar/vector gate between FGS1 and AIRS embeddings
fusion:
  enabled: true
  type: gate
  dim: 256
  gate_type: vector        # options: scalar | vector (vector allows per-dim gating)
  dropout: 0.05
  layer_norm: false
  residual: false
  gate_init: 0.5           # initial gate bias; 0.5 means equal weight to both inputs
  clamp_range: [0.0, 1.0]  # hard clamp on learned gates
  export_step_latents: true