# @package _global_.model.fusion
type: moe
moe:
  num_experts: 4
  expert_hidden: 256
  activation: silu
  dropout: 0.05
  gating:
    source: concat
    hidden: 128
    dropout: 0.05
export:
  gate_values: true
  taps: true
