# configs/symbolic/overrides/base.yaml
#
# Conservative defaults that can be composed everywhere without surprises.

symbolic:
  mode: "soft"                      # ["soft", "hard"]
  weights:
    smoothness_l2: 0.50
    smoothness_fft: 0.35
    nonnegativity: 0.30
    asymmetry: 0.20
    photonic_alignment: 0.40
    molecule_consistency: 0.45
  thresholds:
    violation:
      warn: 0.35
      error: 0.65
  smoothing:
    mu_l2_window_bins: 5
    mu_fft_min_ratio: 0.05
  photonic_alignment:
    enable: true
    max_phase_offset: 0.015         # in orbital phase units
  molecule_windows:
    # Canonical AIRS wavelength bins (indices) by molecule ROIs; adjusted by molecule overrides.
    H2O: [[12,28],[46,63],[102,120],[182,205]]
    CO2: [[130,152],[222,244]]
    CH4: [[70,86],[156,176],[248,266]]
    NH3: [[94,101],[206,214]]
    CO: [[116,128],[270,282]]
  nonnegativity:
    allow_small_eps: true
    eps: 1.0e-6
  corel:
    enable: true
    coverage_target: 0.90
    alpha: 0.10
    calibration_weight: 0.25
  calibration:
    temperature_scale: 1.00
    per_bin_scaling: false

diagnostics:
  flags:
    overlay_symbolic_rules: true
    overlay_fft_spectrum: true
    overlay_entropy_map: true
  exports:
    write_binwise_gll_heatmap: true
    write_symbolic_violation_table: true

events_jsonl:
  enable: true
  path: "artifacts/events/symbolic_events.jsonl"

logs:
  rotate_mb: 8
  max_files: 6
