# Kaggle runtime guardrail: reduce heavy exports, slightly relax caps to avoid stalls
symbolic:
  profile:
    export_detail: "summary"
    caps:
      per_rule_cap: 8.0
  debug:
    log_to_file: true
    sample_planets_for_logs: 4
  export:
    save_rule_maps_npz: false
    save_html_table: true
