# Master Hydra configuration for SpectraMind V50
# Registers logging, sweeper/launcher, and output directories.
# This file anchors all sub-configs in configs/hydra.

hydra:
  run:
    # Default working directory for single runs
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}

  sweep:
    # Base directory for multi-run sweeps
    dir: logs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}

  job:
    name: spectramind_v50
    chdir: true
    # Save Hydra config in each run folder
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: [seed]

  # Include defaults for job_logging and launcher
  defaults:
    - hydra/job_logging: default
    - hydra/launcher: basic
    - hydra/sweeper: basic
