bond_types:
  - id: single
    order: 1
    typical_length_angstrom: [1.09, 1.54] # H-H .. C-C ranges
  - id: double
    order: 2
    typical_length_angstrom: [1.20, 1.34]
  - id: triple
    order: 3
    typical_length_angstrom: [1.09, 1.20]
aromatic:
  planar: true
  resonance: true
