molecules:
  - id: h2o
    name: Water
    formula: H2O
    spectral:
      bands_um: [1.4, 1.9, 2.7, 6.3]
      windows_um: [1.25, 1.65, 2.2]
      references: ["HITRAN", "ExoMol"]
    tags: [exoplanet, atmosphere, biosignature_candidate]
  - id: co2
    name: Carbon Dioxide
    formula: CO2
    spectral:
      bands_um: [2.0, 2.7, 4.3, 15.0]
      references: ["HITRAN", "GEISA"]
    tags: [exoplanet, greenhouse]
  - id: ch4
    name: Methane
    formula: CH4
    spectral:
      bands_um: [1.7, 2.3, 3.3, 7.7]
      references: ["HITRAN", "ExoMol"]
    tags: [exoplanet, reduced_atmospheres]
  - id: o3
    name: Ozone
    formula: O3
    spectral:
      bands_um: [9.6]
      lines_nm: [255]
      references: ["HITRAN"]
    tags: [biosignature_context]
  - id: o2
    name: Molecular Oxygen
    formula: O2
    spectral:
      lines_nm: [690, 760] # A-band ~760 nm
      references: ["HITRAN"]
    tags: [biosignature_context]
