# configs/logging/base.yaml
# Hydra-facing base logging config (dictConfig)
# Note: We explicitly disable Hydra's own job_logging/hydra_logging so our config is authoritative.

defaults:
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

logging:
  version: 1
  disable_existing_loggers: false

  root:
    level: INFO
    handlers: [console]

  formatters:
    simple:
      format: "[%(asctime)s] [%(levelname)s] [%(name)s] - %(message)s"
    json:
      format: '{"time": "%(asctime)s", "level": "%(levelname)s", "logger": "%(name)s", "msg": "%(message)s"}'

  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: simple
      stream: ext://sys.stdout

  loggers:
    spectramind:
      level: INFO
      propagate: true
