# configs/logging/file.yaml
# Rotating file logging: writes logs/v50_debug_log.md (10MB x 5 backups)

defaults:
  - base

logging:
  handlers:
    file:
      class: logging.handlers.RotatingFileHandler
      level: INFO
      formatter: simple
      filename: logs/v50_debug_log.md
      maxBytes: 10485760
      backupCount: 5
  root:
    handlers: [file]
