name: "Simulated Ideal Spectrograph"
telescope:
  aperture_m: 1.2
  f_number: 12.0
  optical_efficiency: 0.9
spectral_range_um: [1.0, 3.0]
channels:
  - name: IDEAL
    range_um: [1.0, 3.0]
    resolving_power: 120
    dispersion: grating
detectors:
  type: "Ideal"
  pixel_scale_arcsec: 0.25
  read_noise_e: 0.0
  dark_current_e_s: 0.0
  saturation_ke: 1000.0
modes: ["transit", "eclipse", "phasecurve"]
pointing:
  rms_jitter_arcsec: 0.0
  long_drift_arcsec: 0.0
photometry:
  precision_ppm_1hr: 1.0
  cadence_s: 5
  throughput_curve: "cal/throughputs/simulated/ideal_flat_1.0.csv"
calibration:
  flat: "cal/flat/sim/ideal_flat.fits"
  dark: "cal/dark/sim/ideal_dark.fits"
  wavelength: "cal/wave/sim/ideal_wave.json"
