name: spectramind-logging-tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  logging-tests:
    name: Logging tests (py${{ matrix.python }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10", "3.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python }}-${{ hashFiles('**/pyproject.toml', '**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies (best-effort)
        run: |
          set -e
          if [ -f "pyproject.toml" ]; then
            pip install -U pip
            # Try optional dev extras first; fall back to generic install.
            (pip install -e .[dev] || pip install -e .) || true
          fi
          if [ -f "requirements.txt" ]; then pip install -r requirements.txt || true; fi
          if [ -f "requirements-dev.txt" ]; then pip install -r requirements-dev.txt || true; fi
          # Ensure test deps available
          pip install pytest pytest-cov pyyaml
      - name: Run pytest (logging tests only) with coverage
        run: |
          pytest src/spectramind/logging/tests -q --disable-warnings \
                 --cov=src --cov-report=xml:coverage.xml --junitxml=pytest-logging.xml
      - name: Upload coverage.xml
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python }}
          path: coverage.xml
      - name: Upload pytest report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-logging-${{ matrix.python }}
          path: pytest-logging.xml
