name: SpectraMind V50 CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'poetry'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run self-test
        run: poetry run python selftest.py --fast
      - name: Run unit tests
        run: poetry run pytest --maxfail=1 --disable-warnings -q
      - name: Lint
        run: poetry run ruff check .
      - name: Type check
        run: poetry run mypy src
      - name: Build docs
        run: |
          pip install mkdocs mkdocs-material
          mkdocs build
      - name: Cache DVC data
        uses: iterative/setup-dvc@v2
      - name: Upload diagnostics dashboard
        uses: actions/upload-artifact@v4
        with:
          name: diagnostics-dashboard
          path: diagnostics_html/
