name: Hydra Trees Sync Check

on:
  pull_request:
  push:
    branches: [ main, master, develop ]

jobs:
  check-hydra-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Hydra sync checker
        run: |
          python tools/check_hydra_sync.py --ci --verbose
