name: logging-selftest
on:
  push:
    paths:
      - 'src/spectramind/logging/**'
      - 'tests/logging/**'
      - '.github/workflows/logging-selftest.yml'
  pull_request:
    paths:
      - 'src/spectramind/logging/**'
      - 'tests/logging/**'
      - '.github/workflows/logging-selftest.yml'
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install project (editable) + pytest
        run: |
          python -m pip install --upgrade pip
          if [ -f pyproject.toml ]; then
            pip install -e ".[dev]" || pip install -e .
          elif [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pytest
          fi
          pip install pytest
      - name: Run smoke tests
        env:
          SPECTRAMIND_LOG_LEVEL: INFO
        run: |
          pytest -q tests/logging/test_logging_smoke.py
