name: Security Scan

on:
  schedule:
    - cron: "0 3 * * 0"
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install security tools
        run: pip install pip-audit bandit
      - name: Python dependency audit
        run: pip-audit
      - name: Bandit security scan
        run: bandit -r src
